on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: Deploy to JAJUWA.PL
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files with JAJUWA.PL
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          port: 21
          protocol: ftps
          exclude: |
            .eslintrc.json
            .gitignore
            package-lock.json
            package.json
            **/.git**
            **/.git*/**
            **/.git**
            **/.git*/**